Min ruby version is now 2.0 instead of 1.9.3
$gem install capistrano
ERROR:  Error installing capistrano:
        net-ssh requires Ruby version >= 2.0.